name: Public Snapshot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install python-dotenv requests

    - name: Generate snapshot
      env:
        NOTION_API: ${{ secrets.NOTION_API }}
      run: |
        python scripts/notion_task_manager.py read || true
        python scripts/generate_tasks_md.py || true
        python scripts/compile_project_snapshot.py --no-pull

        # Copy to consistent name
        SNAPSHOT_FILE=$(ls -t snapshots/project_snapshot_*.md | head -1)
        cp "$SNAPSHOT_FILE" LATEST_SNAPSHOT.md

    - name: Checkout public repo
      uses: actions/checkout@v3
      with:
        repository: betaranch/santas-workshop-public
        token: ${{ secrets.GITHUB_TOKEN }}
        path: public

    - name: Update public snapshot
      run: |
        # Copy snapshot to public repo
        cp LATEST_SNAPSHOT.md public/

        # Also create a simple HTML viewer
        cat > public/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Project Snapshot</title>
            <meta charset="UTF-8">
            <style>
                body { font-family: Arial; max-width: 900px; margin: 0 auto; padding: 20px; }
                button { background: #0070f3; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; font-size: 16px; margin: 10px; }
                pre { display: none; white-space: pre-wrap; background: #f5f5f5; padding: 20px; margin-top: 20px; }
                .message { padding: 10px; background: #d4edda; color: #155724; border-radius: 5px; }
            </style>
        </head>
        <body>
            <h1>Santa's Workshop - Project Snapshot</h1>
            <p>Auto-updates every 6 hours</p>
            <button onclick="copySnapshot()">📋 Copy to Clipboard</button>
            <a href="LATEST_SNAPSHOT.md" download><button>⬇️ Download</button></a>
            <div id="message"></div>
            <pre id="content"></pre>
            <script>
                fetch('LATEST_SNAPSHOT.md')
                    .then(r => r.text())
                    .then(text => document.getElementById('content').textContent = text);

                function copySnapshot() {
                    const content = document.getElementById('content').textContent;
                    navigator.clipboard.writeText(content).then(() => {
                        const msg = document.getElementById('message');
                        msg.textContent = '✅ Copied! Paste into any AI assistant.';
                        msg.className = 'message';
                        setTimeout(() => msg.textContent = '', 5000);
                    });
                }
            </script>
        </body>
        </html>
        EOF

        # Commit and push
        cd public
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "📸 Update snapshot - $(date +'%Y-%m-%d %H:%M')"
        git push || echo "No changes to push"