name: Simple Auto Snapshot

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

  # Manual trigger
  workflow_dispatch:

  # On push to main
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install python-dotenv requests

    - name: Generate snapshot
      env:
        NOTION_API: ${{ secrets.NOTION_API }}
      run: |
        # Try to pull latest from Notion (optional)
        python scripts/notion_task_manager.py read || true
        python scripts/generate_tasks_md.py || true

        # Generate the snapshot
        python scripts/compile_project_snapshot.py --no-pull

        # Copy to root with consistent name
        cp snapshots/project_snapshot_*.md LATEST_SNAPSHOT.md

    - name: Commit snapshot
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add LATEST_SNAPSHOT.md
        git diff --staged --quiet || git commit -m "📸 Auto-update snapshot - $(date +'%Y-%m-%d %H:%M')"
        git push || echo "No changes"